name: Laba5
on: push
jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Install dependencies
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ libstdc++6
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: Laba5
  tests:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: Laba5
          fetch-depth: 0

      - name: ubuntu
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ libstdc++6
          chmod +x ./build/tests/tests
          ./build/tests/tests
        
      - name: windows
        if: matrix.os == 'windows-latest'
        run: |
          & '.\\build\\tests\\tests.exe'